#!/bin/bash
#
# DESCRIPTION
# Download original EPUB files from https://www.fadedpage.com.
#
# USAGE
#
#   000-download
#
# ADDITIONAL INFORMATION
# Faded Page is an archive of eBooks that are provided completely free to
# everyone.

EPUBS_DIR='site/static/epubs'

# Map of download URLs -> EPUB filenames
MAP=(
  'https://www.fadedpage.com/link.php?file=20151102.epub,01-james-bond.epub'
  'https://www.fadedpage.com/link.php?file=20151111.epub,02-james-bond.epub'
  'https://www.fadedpage.com/link.php?file=20150804.epub,03-james-bond.epub'
  'https://www.fadedpage.com/link.php?file=20170328.epub,04-james-bond.epub'
  'https://www.fadedpage.com/link.php?file=20160104.epub,05-james-bond.epub'
  'https://www.fadedpage.com/link.php?file=20170725.epub,06-james-bond.epub'
  'https://www.fadedpage.com/link.php?file=20160105.epub,07-james-bond.epub'
  'https://www.fadedpage.com/link.php?file=20170435.epub,08-james-bond.epub'
  'https://www.fadedpage.com/link.php?file=20191233.epub,09-james-bond.epub'
  'https://www.fadedpage.com/link.php?file=20151114.epub,10-james-bond.epub'
  'https://www.fadedpage.com/link.php?file=20180448.epub,11-james-bond.epub'
  'https://www.fadedpage.com/link.php?file=20171118.epub,12-james-bond.epub'
  'https://www.fadedpage.com/link.php?file=20180848.epub,13-james-bond.epub'
  'https://www.fadedpage.com/link.php?file=20190516.epub,14-james-bond.epub'
  'https://www.fadedpage.com/link.php?file=20190513.epub,15-james-bond.epub'
)

for elem in "${MAP[@]}"; do
  url="${elem%,*}"
  filename="${elem#*,}"
  echo "Downloading ${filename}..."
  # NOTE: The session ID must be provided in the request to download the file.
  while IFS=':' read -r key value; do
    case "${key}" in
      "set-cookie") SET_COOKIE="${value}";;
    esac
  done < <(curl --silent --head --location "${url}")
  PHPSESSID="${SET_COOKIE#*PHPSESSID=}";PHPSESSID="${PHPSESSID%;*}"
  curl --silent -X GET -L "${url}" -o "${EPUBS_DIR}/${filename}" \
    -H "Cookie: PHPSESSID=${PHPSESSID}"
done
