#!/bin/bash
#
# DESCRIPTION
# Download original EPUB files from https://www.fadedpage.com.
#
# USAGE
#
#   000-download
#
# ADDITIONAL INFORMATION
# Faded Page is an archive of eBooks that are provided completely free to
# everyone.

# Map of download URLs -> EPUB filenames
MAP=(
  'https://www.fadedpage.com/link.php?file=20151102.epub,01-casino-royale.epub'
  'ttps://www.fadedpage.com/link.php?file=20151111.epub,02-live-and-let-die.epubh'
  'https://www.fadedpage.com/link.php?file=20150804.epub,03-moonraker.epub'
  'https://www.fadedpage.com/link.php?file=20170328.epub,04-diamonds-are-forever.epub'
  'https://www.fadedpage.com/link.php?file=20160104.epub,05-from-russia-with-love.epub'
  'https://www.fadedpage.com/link.php?file=20170725.epub,06-dr-no.epub'
  'https://www.fadedpage.com/link.php?file=20160105.epub,07-goldfinger.epub'
  'https://www.fadedpage.com/link.php?file=20170435.epub,08-for-your-eyes-only.epub'
  'https://www.fadedpage.com/link.php?file=20191233.epub,09-thunderball.epub'
  'https://www.fadedpage.com/link.php?file=20151114.epub,10-the-spy-who-loved-me.epub'
  'https://www.fadedpage.com/link.php?file=20180448.epub,11-on-her-majestys-secret-service.epub'
  'https://www.fadedpage.com/link.php?file=20171118.epub,12-you-only-live-twice.epub'
  'https://www.fadedpage.com/link.php?file=20180848.epub,13-the-man-with-the-golden-gun.epub'
  'https://www.fadedpage.com/link.php?file=20190516.epub,14-octopussy.epub'
  'https://www.fadedpage.com/link.php?file=20190513.epub,15-the-living-daylights.epub'
)

for elem in "${MAP[@]}"; do
  url="${elem%,*}"
  filename="${elem#*,}"
  echo "Downloading ${filename}..."
  # NOTE: The session ID must be provided in the request to download the file.
  while IFS=':' read -r key value; do
    case "${key}" in
      "set-cookie") SET_COOKIE="${value}";;
    esac
  done < <(curl --silent --head --location "${url}")
  PHPSESSID="${SET_COOKIE#*PHPSESSID=}";PHPSESSID="${PHPSESSID%;*}"
  curl --silent -X GET -L "${url}" -o "${filename}" \
    -H "Cookie: PHPSESSID=${PHPSESSID}"
done
