#!/bin/bash
#
# DESCRIPTION
# Unzip original EPUB files.
#
# USAGE
#
#   001-unzip

CONTENT_DIR='site/content'
EPUBS_DIR='site/static/epubs'

for f in "${EPUBS_DIR}"/*.epub; do
  dir=$(basename "${f}" .epub)
  rm -rf "${CONTENT_DIR:?}/${dir}"
  unzip "${f}" -d "${CONTENT_DIR}/${dir}"
done
