#!/bin/bash
#
# DESCRIPTION
# Unzip original EPUB files.
#
# USAGE
#
#   001-unzip

EPUBS_DIR='site/static/epubs'

for f in "${EPUBS_DIR}"/*.epub; do
  dir=$(basename "${f}" .epub)
  rm -rf "site/content/${dir}"
  unzip "${f}" -d "site/content/${dir}"
done
