#!/bin/bash
#
# DESCRIPTION
# Zip extracted files to EPUB files.
#
# USAGE
#
#   002-zip

CONTENT_DIR='site/content'
EPUBS_DIR='site/static/epubs'

for f in "${EPUBS_DIR}"/*.epub; do
  rm -f "${f}"
  dir=$(basename "${f}" .epub)
  pushd "${CONTENT_DIR}/${dir}" >/dev/null || exit
  # NOTE: The mimetype file must be the first file in the archive.
  zip -rX "../../../${EPUBS_DIR}/$(basename "$(realpath .)").epub" mimetype $(ls | xargs echo | sed 's/mimetype//g')
  popd >/dev/null || exit
done
